### ISSUE TITLE
Debounce implementation

### ISSUE THREAD

**Issue by andrejkaurin** [yuku/textcomplete#106]
What are options to implement debounce so search is not called until user stops typing?

**Comment by noahfpf** [comment]
For anyone looking to debounce the new `@textcomplete/core` version, you can't debounce your strategy's async `search` method because it is only called once until it returns results (see the `isQueryInFlight` property in https://github.com/yuku/textcomplete/blob/v0.1.10/packages/textcomplete-core/src/Textcomplete.ts#L57).

However, you can easily apply a debounce method to the `Textcomplete` trigger method, e.g.:

```javascript
import debounce from 'lodash/debounce';

const textcomplete = new Textcomplete(...);

textcomplete.trigger = debounce(textcomplete.trigger, 400);
```

**Comment by brenc** [comment]
For those using Typescript and eslint:
```typescript
textcomplete.trigger =
  ((originalTrigger: (beforeCursor: string) => Textcomplete) => {
    const debouncedTrigger = debounce(originalTrigger, 500);
    return (beforeCursor: string): Textcomplete => {
      debouncedTrigger(beforeCursor);
      return textcomplete;
    };
  })(textcomplete.trigger.bind(textcomplete));
```
Copilot helped me figure this out. I couldn't find another way to get this to work while still satisfying both ts and eslint.

<details><summary>If you want a detailed explanation of what this code is doing:</summary>
<p>

The active selection is a piece of TypeScript code that modifies the trigger method of a Textcomplete instance. The Textcomplete class is typically used for autocompletion functionality, and the trigger method is used to manually trigger the autocompletion.

The trigger method is being replaced with a new function that debounces the original trigger method. Debouncing is a technique used to limit the rate at which a function can execute, which is useful in scenarios like autocompletion where you don't want to make a new API request with every keystroke.

The new function is created using an Immediately Invoked Function Expression (IIFE). The IIFE takes the original trigger method as an argument, binds it to the [textcomplete](vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/code/electron-sandbox/workbench/workbench.html) instance, and returns a debounced version of it. The debounced function is created using the debounce function, which is typically imported from a library like lodash. The debounce function takes two arguments: the function to debounce and the delay in milliseconds. In this case, the delay is set to 500 milliseconds, meaning the trigger method won't be called until 500 milliseconds have passed since the last time it was invoked.

The new function returned by the IIFE has the same signature as the original trigger method: it takes a beforeCursor string as an argument and returns a Textcomplete instance. However, instead of executing the original trigger method immediately, it calls the debounced version of it. After calling the debounced function, it always returns the [textcomplete](vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/code/electron-sandbox/workbench/workbench.html) instance, ensuring that the return type of the new trigger method is always Textcomplete.

This code is a good example of how you can modify the behavior of a method from a class that you don't own in a type-safe way in TypeScript. It also demonstrates the use of debouncing to improve the performance of an autocompletion feature.

</p>
</details> 


Thank you @noahfpf for pointing me in the right direction.
