### ISSUE TITLE
Enter key on summernote

### ISSUE THREAD

**Issue by rodrigosol** [yuku/textcomplete#190]
Hi there,

Thanks for this great work! I am using jquery-textcomplete with summernote. Everything goes ok, except the fact that is not possible to select an item using the enter key.

I tried many hacks without success such as:
-  Fire textComplete:select event externally;
-  Fire click and mousedown over list item;

Do you guys have any clue?

All the best

**Comment by timeless161** [comment]
I'm having this same issue, the problem seems to be the selection is changing to a new tag prior to the text insert.  When summernote detects a return, a <p> or <br> tag is thrown into the div, by the time the select/getTextFromHeadToCaret function fires, the selection is in the wrong tag causing the text complete to fail.

**Comment by timeless161** [comment]
The way to easily fix this is to remove the keymap in summernote

'ENTER': 'insertParagraph'

to 

'ENTER': ''

**Comment by mbeech** [comment]
Struggling with this too. It's not just on Summernote, also seeing it on https://github.com/basecamp/trix.
