### ISSUE TITLE
Navigating through text in the control pops up auto-completer for no reason

### ISSUE THREAD

**Issue by ramraid** [yuku/textcomplete#41]
Navigating within the textarea using arrow keys pops up the auto-completer if the word under the cursor matches the "match" regular expression. 

There should be a check for which key is pressed.

**Comment by mejmt** [comment]
This is still an issue. It only filters out the up and down arrows, but should also filter left and right arrows. It's very annoying to have just autocompleted something, then have the dropdown show back up just because you press the left arrow to go back and change something else.

It should only trigger on actual content change, so I would actually argue that the list of filtered keys should be much larger or potentially even a whitelist. For instance, autocompleting then moving caret with mouse and pressing an F-key (or even Shift or Ctrl) will also trigger the dropdown.

**Comment by mejmt** [comment]
Here's what I'm using in my version to fix this issue (in `Adapter._skipSearch`):
```javascript
switch (clickEvent.keyCode) {
  case 13: // ENTER
  case 16: // SHIFT
  case 17: // Ctrl
  case 18: // ALT
  case 19: // PAUSE, BREAK
  case 20: // CAPS LOCK
  case 27: // ESC
  case 33: // PAGE UP
  case 34: // PAGE DOWN
  case 35: // END
  case 36: // HOME
  case 37: // LEFT
  case 38: // UP
  case 39: // RIGHT
  case 40: // DOWN
  case 44: // PRNT SCRN
  case 45: // INSERT
  case 91: // WIN KEY
  case 93: // WIN MENU
  case 112: // F1
  case 113: // F2
  case 114: // F3
  case 115: // F4
  case 116: // F5
  case 117: // F6
  case 118: // F7
  case 119: // F8
  case 120: // F9
  case 121: // F10
  case 122: // F11
  case 123: // F12
  case 144: // NUM LOCK
  case 145: // SCROLL LOCK
    return true;
}
```
